services:
  client:
    build: ./roommate-app
    ports:
      - "5173:5173"
    volumes:
      - ./roommate-app:/app
      - /app/node_modules
    depends_on:
      - server

  server:
    user: root
    build: ./roommate-server
    ports:
      - "5000:5000"
    volumes:
      - ./roommate-server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DATABASE_URL=postgres://postgres:password@db:5432/roommate
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
    depends_on:
      - db
    command: npm run dev

  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: roommate
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
